import type { AppState, Campaign } from "@/types";

export const campaigns: Campaign[] = [
  {
    id: "lazhi-roujiamo",
    brand: "尖锋食客",
    title: "腊汁肉夹馍",
    subtitle: "成品样已到，试用方案与正式主图确认中",
    category: "roujiamo",
    price: 0,
    refundAmount: 0,
    quota: 0,
    applications: 0,
    deadline: "试用方案确认后公布",
    feedbackDays: 7,
    accent: "#b66a3c",
    launchStatus: "preparing",
    sampleStatus: ["8.17 成品已给 8 个"],
    visualLabel: "腊汁\n肉夹馍",
    requirements: ["试用价格与名额确认后开放申请", "正式包装和反馈要求将在开放前公布", "拍摄样状态仅作项目筹备记录"],
  },
  {
    id: "butter-saqima",
    brand: "尖锋食客",
    title: "黄油沙琪玛",
    subtitle: "内容物与成品样均已到位，试用方案确认中",
    category: "saqima",
    price: 0,
    refundAmount: 0,
    quota: 0,
    applications: 0,
    deadline: "试用方案确认后公布",
    feedbackDays: 7,
    accent: "#e3a62f",
    launchStatus: "preparing",
    sampleStatus: ["8.14 内容物已给 2 盒", "8.17 成品已给 10 盒"],
    visualLabel: "黄油\n沙琪玛",
    requirements: ["试用价格与名额确认后开放申请", "正式包装和反馈要求将在开放前公布", "拍摄样状态仅作项目筹备记录"],
  },
  {
    id: "butter-scallion-nougat-cracker",
    brand: "尖锋食客",
    title: "黄油香葱牛扎夹心饼干",
    subtitle: "内容物已到，包装样正在到样流程中",
    category: "cracker",
    price: 0,
    refundAmount: 0,
    quota: 0,
    applications: 0,
    deadline: "试用方案确认后公布",
    feedbackDays: 7,
    accent: "#c17d3f",
    launchStatus: "preparing",
    sampleStatus: ["8.14 内容物已给 5 盒", "8.18 内容物已给 5 盒", "包装 8.19 到"],
    visualLabel: "香葱牛扎\n夹心饼干",
    requirements: ["试用价格与名额确认后开放申请", "正式包装和反馈要求将在开放前公布", "拍摄样状态仅作项目筹备记录"],
  },
  {
    id: "prebiotic-hawthorn-stick",
    brand: "尖锋食客",
    title: "益生元山楂棒",
    subtitle: "内容物已到，等待包装样确认后进入试用排期",
    category: "hawthorn",
    price: 0,
    refundAmount: 0,
    quota: 0,
    applications: 0,
    deadline: "试用方案确认后公布",
    feedbackDays: 7,
    accent: "#d94e3d",
    launchStatus: "preparing",
    sampleStatus: ["8.14 内容物已给 21 个", "包装 8.19 到"],
    visualLabel: "益生元\n山楂棒",
    requirements: ["试用价格与名额确认后开放申请", "正式包装和反馈要求将在开放前公布", "拍摄样状态仅作项目筹备记录"],
  },
  {
    id: "seaweed-shrimp-soup",
    brand: "尖锋食客",
    title: "紫菜虾皮汤料",
    subtitle: "首批内容物已到，继续等待内容物与包装样",
    category: "soup",
    price: 0,
    refundAmount: 0,
    quota: 0,
    applications: 0,
    deadline: "试用方案确认后公布",
    feedbackDays: 7,
    accent: "#285d4c",
    launchStatus: "preparing",
    sampleStatus: ["8.14 内容物已给 4 包", "内容物 8.19 到", "包装样 8.22 到"],
    visualLabel: "紫菜虾皮\n汤料",
    requirements: ["试用价格与名额确认后开放申请", "正式包装和反馈要求将在开放前公布", "拍摄样状态仅作项目筹备记录"],
  },
  {
    id: "juicy-beef-dumpling",
    brand: "尖锋食客",
    title: "爆汁牛肉手作锅贴",
    subtitle: "内容物已到，包装样确认后进入试用排期",
    category: "dumpling",
    price: 0,
    refundAmount: 0,
    quota: 0,
    applications: 0,
    deadline: "试用方案确认后公布",
    feedbackDays: 7,
    accent: "#4d8468",
    launchStatus: "preparing",
    sampleStatus: ["8.18 给内容物 10 盒", "包装 8.22 到"],
    visualLabel: "爆汁牛肉\n手作锅贴",
    requirements: ["试用价格与名额确认后开放申请", "正式包装和反馈要求将在开放前公布", "拍摄样状态仅作项目筹备记录"],
  },
  {
    id: "melon-craft-beer",
    brand: "尖锋食客",
    title: "蜜瓜精酿啤酒",
    subtitle: "罐装样已到，等待外箱与大货样确认",
    category: "beer",
    price: 0,
    refundAmount: 0,
    quota: 0,
    applications: 0,
    deadline: "试用方案确认后公布",
    feedbackDays: 7,
    accent: "#6db9bd",
    launchStatus: "preparing",
    sampleStatus: ["8.17 已给 36 罐", "外箱＋大货样 8.22 到"],
    visualLabel: "蜜瓜\n精酿",
    requirements: ["仅面向达到法定饮酒年龄的用户开放", "试用价格、名额与反馈要求确认后开放申请", "拍摄样状态仅作项目筹备记录"],
  },
  {
    id: "milk-cake",
    brand: "尖锋食客",
    title: "鲜奶小蛋糕新品试吃",
    subtitle: "像刚出炉一样柔软，等你说真话",
    category: "bakery",
    price: 39.9,
    refundAmount: 39.9,
    quota: 500,
    applications: 1268,
    deadline: "08月30日 22:00",
    feedbackDays: 7,
    accent: "#f47a4a",
    requirements: ["签收后 7 天内完成反馈", "提交不少于 50 字的真实体验", "上传 1–3 张真实试用图片"],
    launchStatus: "open",
  },
  {
    id: "osmanthus-tea",
    brand: "山间茶事",
    title: "冷泡桂花乌龙首发体验",
    subtitle: "一瓶茶，看看桂花能不能留住夏天",
    category: "tea",
    price: 49,
    refundAmount: 49,
    quota: 300,
    applications: 742,
    deadline: "09月02日 18:00",
    feedbackDays: 5,
    accent: "#c69b3c",
    requirements: ["连续饮用至少 2 次", "评价香气、甜度与回甘", "上传至少 1 张饮用场景图"],
    launchStatus: "open",
  },
  {
    id: "seaweed-crisp",
    brand: "海风制造",
    title: "烘烤海苔脆片口感共创",
    subtitle: "不是找夸奖，是一起把脆度调准",
    category: "snack",
    price: 29.9,
    refundAmount: 29.9,
    quota: 800,
    applications: 955,
    deadline: "09月06日 20:00",
    feedbackDays: 6,
    accent: "#1f6f5e",
    requirements: ["对比日常购买的同类产品", "完成 4 项结构化评分", "写明最希望改进的一点"],
    launchStatus: "open",
  },
];

export const initialState: AppState = {
  participations: [
    {
      id: "participation-feedback",
      campaignId: "osmanthus-tea",
      userId: "demo-user",
      userName: "林小雨",
      city: "杭州",
      age: "25-34",
      reason: "平时会在办公室泡冷泡茶，想比较桂花香是不是自然。",
      status: "feedback_available",
      submittedAt: "2026-08-16T08:30:00.000Z",
      qualificationToken: "QT-TEA-8F4A",
      trackingNumber: "SF143920260824",
      feedbackDeadline: "2026-08-29T15:00:00.000Z",
    },
    {
      id: "participation-complete",
      campaignId: "seaweed-crisp",
      userId: "demo-user",
      userName: "林小雨",
      city: "杭州",
      age: "25-34",
      reason: "经常买海苔零食，能给出具体对比。",
      status: "completed",
      submittedAt: "2026-08-01T03:20:00.000Z",
      qualificationToken: "QT-SEA-2C18",
      trackingNumber: "YT882601938",
      feedbackDeadline: "2026-08-18T12:00:00.000Z",
      refundIdempotencyKey: "refund-participation-complete",
      feedback: {
        overall: 4,
        taste: 4,
        packaging: 5,
        value: 4,
        repurchase: "会",
        liked: "脆度好，海苔香气干净。",
        improve: "希望尾味再少一点甜。",
        review: "独立小包装很方便，开袋没有油腻感。第一口的海苔味很清楚，脆度保持得也好；吃到后面甜味稍微明显，如果能更克制一点会更耐吃。",
        photos: 2,
      },
    },
    {
      id: "application-li",
      campaignId: "milk-cake",
      userId: "applicant-li",
      userName: "李知夏",
      city: "上海",
      age: "25-34",
      reason: "每周会买两次早餐糕点，能对比便利店和烘焙店的鲜奶蛋糕。",
      status: "under_review",
      submittedAt: "2026-08-24T02:16:00.000Z",
    },
    {
      id: "application-zhou",
      campaignId: "milk-cake",
      userId: "applicant-zhou",
      userName: "周元青",
      city: "苏州",
      age: "35-44",
      reason: "家里有小朋友，关注配料、甜度和独立包装是否方便。",
      status: "under_review",
      submittedAt: "2026-08-24T01:42:00.000Z",
    },
    {
      id: "refund-exception",
      campaignId: "milk-cake",
      userId: "applicant-wang",
      userName: "王禾",
      city: "宁波",
      age: "25-34",
      reason: "烘焙爱好者。",
      status: "refund_failed",
      submittedAt: "2026-08-06T01:42:00.000Z",
      qualificationToken: "QT-CAKE-92D1",
      refundIdempotencyKey: "refund-refund-exception",
      refundFailureReason: "原支付订单已关闭，需要人工核对支付渠道",
    },
  ],
  events: [],
  notifications: [
    { id: "n-1", title: "反馈任务已开启", body: "桂花乌龙已签收，请在 5 天内完成真实反馈。", read: false, createdAt: "今天 10:20" },
    { id: "n-2", title: "退款已到账", body: "海苔脆片试用款 ¥29.90 已原路退回。", read: true, createdAt: "08月19日" },
  ],
};

export const statusLabels: Record<string, string> = {
  applied: "已申请",
  under_review: "待审核",
  rejected: "未通过",
  approved: "已通过",
  purchase_pending: "待购买",
  purchased: "已付款",
  shipment_pending: "待发货",
  shipped: "运输中",
  delivered: "已签收",
  feedback_available: "待反馈",
  feedback_submitted: "反馈待审核",
  feedback_revision_required: "需补充反馈",
  feedback_resubmitted: "已重新提交",
  feedback_approved: "反馈已通过",
  refund_pending: "待退款",
  refund_processing: "退款中",
  refund_success: "退款成功",
  refund_failed: "退款异常",
  completed: "已完成",
  expired: "已过期",
  cancelled: "已取消",
};
