import type { AppState, Campaign } from "@/types";

export const campaigns: Campaign[] = [
  {
    id: "milk-cake",
    brand: "尖锋食客",
    title: "鲜奶小蛋糕新品试吃",
    subtitle: "像刚出炉一样柔软，等你说真话",
    category: "bakery",
    price: 39.9,
    refundAmount: 39.9,
    quota: 500,
    applications: 1268,
    deadline: "08月30日 22:00",
    feedbackDays: 7,
    accent: "#f47a4a",
    requirements: ["签收后 7 天内完成反馈", "提交不少于 50 字的真实体验", "上传 1–3 张真实试用图片"],
  },
  {
    id: "osmanthus-tea",
    brand: "山间茶事",
    title: "冷泡桂花乌龙首发体验",
    subtitle: "一瓶茶，看看桂花能不能留住夏天",
    category: "tea",
    price: 49,
    refundAmount: 49,
    quota: 300,
    applications: 742,
    deadline: "09月02日 18:00",
    feedbackDays: 5,
    accent: "#c69b3c",
    requirements: ["连续饮用至少 2 次", "评价香气、甜度与回甘", "上传至少 1 张饮用场景图"],
  },
  {
    id: "seaweed-crisp",
    brand: "海风制造",
    title: "烘烤海苔脆片口感共创",
    subtitle: "不是找夸奖，是一起把脆度调准",
    category: "snack",
    price: 29.9,
    refundAmount: 29.9,
    quota: 800,
    applications: 955,
    deadline: "09月06日 20:00",
    feedbackDays: 6,
    accent: "#1f6f5e",
    requirements: ["对比日常购买的同类产品", "完成 4 项结构化评分", "写明最希望改进的一点"],
  },
];

export const initialState: AppState = {
  participations: [
    {
      id: "participation-feedback",
      campaignId: "osmanthus-tea",
      userId: "demo-user",
      userName: "林小雨",
      city: "杭州",
      age: "25-34",
      reason: "平时会在办公室泡冷泡茶，想比较桂花香是不是自然。",
      status: "feedback_available",
      submittedAt: "2026-08-16T08:30:00.000Z",
      qualificationToken: "QT-TEA-8F4A",
      trackingNumber: "SF143920260824",
      feedbackDeadline: "2026-08-29T15:00:00.000Z",
    },
    {
      id: "participation-complete",
      campaignId: "seaweed-crisp",
      userId: "demo-user",
      userName: "林小雨",
      city: "杭州",
      age: "25-34",
      reason: "经常买海苔零食，能给出具体对比。",
      status: "completed",
      submittedAt: "2026-08-01T03:20:00.000Z",
      qualificationToken: "QT-SEA-2C18",
      trackingNumber: "YT882601938",
      feedbackDeadline: "2026-08-18T12:00:00.000Z",
      refundIdempotencyKey: "refund-participation-complete",
      feedback: {
        overall: 4,
        taste: 4,
        packaging: 5,
        value: 4,
        repurchase: "会",
        liked: "脆度好，海苔香气干净。",
        improve: "希望尾味再少一点甜。",
        review: "独立小包装很方便，开袋没有油腻感。第一口的海苔味很清楚，脆度保持得也好；吃到后面甜味稍微明显，如果能更克制一点会更耐吃。",
        photos: 2,
      },
    },
    {
      id: "application-li",
      campaignId: "milk-cake",
      userId: "applicant-li",
      userName: "李知夏",
      city: "上海",
      age: "25-34",
      reason: "每周会买两次早餐糕点，能对比便利店和烘焙店的鲜奶蛋糕。",
      status: "under_review",
      submittedAt: "2026-08-24T02:16:00.000Z",
    },
    {
      id: "application-zhou",
      campaignId: "milk-cake",
      userId: "applicant-zhou",
      userName: "周元青",
      city: "苏州",
      age: "35-44",
      reason: "家里有小朋友，关注配料、甜度和独立包装是否方便。",
      status: "under_review",
      submittedAt: "2026-08-24T01:42:00.000Z",
    },
    {
      id: "refund-exception",
      campaignId: "milk-cake",
      userId: "applicant-wang",
      userName: "王禾",
      city: "宁波",
      age: "25-34",
      reason: "烘焙爱好者。",
      status: "refund_failed",
      submittedAt: "2026-08-06T01:42:00.000Z",
      qualificationToken: "QT-CAKE-92D1",
      refundIdempotencyKey: "refund-refund-exception",
      refundFailureReason: "原支付订单已关闭，需要人工核对支付渠道",
    },
  ],
  events: [],
  notifications: [
    { id: "n-1", title: "反馈任务已开启", body: "桂花乌龙已签收，请在 5 天内完成真实反馈。", read: false, createdAt: "今天 10:20" },
    { id: "n-2", title: "退款已到账", body: "海苔脆片试用款 ¥29.90 已原路退回。", read: true, createdAt: "08月19日" },
  ],
};

export const statusLabels: Record<string, string> = {
  applied: "已申请",
  under_review: "待审核",
  rejected: "未通过",
  approved: "已通过",
  purchase_pending: "待购买",
  purchased: "已付款",
  shipment_pending: "待发货",
  shipped: "运输中",
  delivered: "已签收",
  feedback_available: "待反馈",
  feedback_submitted: "反馈待审核",
  feedback_revision_required: "需补充反馈",
  feedback_resubmitted: "已重新提交",
  feedback_approved: "反馈已通过",
  refund_pending: "待退款",
  refund_processing: "退款中",
  refund_success: "退款成功",
  refund_failed: "退款异常",
  completed: "已完成",
  expired: "已过期",
  cancelled: "已取消",
};
